#!/bin/sh /etc/rc.common
# Basic init script for door system
# Make sure /etc/rc.d/S80phpdoor is symlinked to this file.

START=80
APP=`which php-cli`
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
        $APP /srv/www/door-server/server.php
}

stop() {
       killall  $APP
}

~
